[install]
is_configured = 1

[ui]
is_visible = 0
label = Linux File Inputs

[launcher]
author = Splunk Learn Forwarding
description = Monitors generated lab application logs on the universal forwarder.
version = 0.1.0

