[monitor:///var/log/lab/app.log]
disabled = 0
index = lab_file
sourcetype = lab:app
host_segment = 3
followTail = 0

[monitor:///var/log/lab/events.json]
disabled = 0
index = lab_json
sourcetype = lab:json
host_segment = 3
followTail = 0

[monitor:///var/log/lab/otel.json]
disabled = 0
index = lab_otel
sourcetype = lab:otel
host_segment = 3
followTail = 0

[monitor:///var/log/lab/events.xml]
disabled = 0
index = lab_xml
sourcetype = lab:xml
host_segment = 3
followTail = 0

[monitor:///var/log/lab/pii.log]
disabled = 0
index = lab_masked
sourcetype = lab:masked
host_segment = 3
followTail = 0

