[script://$SPLUNK_HOME/etc/apps/TA_scripted_inputs/bin/python_scripted_input.py]
disabled = 0
interval = 30
index = lab_scripted
sourcetype = lab:scripted:python

[script://$SPLUNK_HOME/etc/apps/TA_scripted_inputs/bin/bash_scripted_input.sh]
disabled = 0
interval = 30
index = lab_scripted
sourcetype = lab:scripted:bash

