[global]
repositoryLocation = $SPLUNK_HOME/etc/deployment-apps

[serverClass:direct_universal_forwarders]
whitelist.0 = universal-forwarder

[serverClass:direct_universal_forwarders:app:TA_common_outputs]
restartSplunkd = true

[serverClass:direct_universal_forwarders:app:TA_linux_file_inputs]
restartSplunkd = true

[serverClass:direct_universal_forwarders:app:TA_network_inputs]
restartSplunkd = true

[serverClass:via_heavy_universal_forwarders]
whitelist.0 = universal-forwarder-via-heavy

[serverClass:via_heavy_universal_forwarders:app:TA_outputs_to_heavy]
restartSplunkd = true

[serverClass:via_heavy_universal_forwarders:app:TA_linux_file_inputs]
restartSplunkd = true

[serverClass:via_heavy_universal_forwarders:app:TA_network_inputs]
restartSplunkd = true

[serverClass:heavy_forwarders]
whitelist.0 = heavy-forwarder

[serverClass:heavy_forwarders:app:TA_common_outputs]
restartSplunkd = true

[serverClass:heavy_forwarders:app:TA_heavy_forwarder_receiving]
restartSplunkd = true

[serverClass:heavy_forwarders:app:TA_heavy_forwarder_parsing]
restartSplunkd = true

[serverClass:heavy_forwarders:app:TA_scripted_inputs]
restartSplunkd = true

