[install]
is_configured = 1

[ui]
is_visible = 0
label = Lab Index And Receiver

[launcher]
author = Learn Splunk
description = Creates the lab index and enables receiving for forwarders.
version = 0.1.0

