[lab_file]
homePath = $SPLUNK_DB/lab_file/db
coldPath = $SPLUNK_DB/lab_file/colddb
thawedPath = $SPLUNK_DB/lab_file/thaweddb

[lab_tcp]
homePath = $SPLUNK_DB/lab_tcp/db
coldPath = $SPLUNK_DB/lab_tcp/colddb
thawedPath = $SPLUNK_DB/lab_tcp/thaweddb

[lab_udp]
homePath = $SPLUNK_DB/lab_udp/db
coldPath = $SPLUNK_DB/lab_udp/colddb
thawedPath = $SPLUNK_DB/lab_udp/thaweddb

[lab_json]
homePath = $SPLUNK_DB/lab_json/db
coldPath = $SPLUNK_DB/lab_json/colddb
thawedPath = $SPLUNK_DB/lab_json/thaweddb

[lab_xml]
homePath = $SPLUNK_DB/lab_xml/db
coldPath = $SPLUNK_DB/lab_xml/colddb
thawedPath = $SPLUNK_DB/lab_xml/thaweddb

[lab_hec]
homePath = $SPLUNK_DB/lab_hec/db
coldPath = $SPLUNK_DB/lab_hec/colddb
thawedPath = $SPLUNK_DB/lab_hec/thaweddb

[lab_scripted]
homePath = $SPLUNK_DB/lab_scripted/db
coldPath = $SPLUNK_DB/lab_scripted/colddb
thawedPath = $SPLUNK_DB/lab_scripted/thaweddb

[lab_masked]
homePath = $SPLUNK_DB/lab_masked/db
coldPath = $SPLUNK_DB/lab_masked/colddb
thawedPath = $SPLUNK_DB/lab_masked/thaweddb

