[lab:app]
SHOULD_LINEMERGE = false
TIME_PREFIX = ts=
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
TRUNCATE = 10000

[lab:tcp]
SHOULD_LINEMERGE = false
TIME_PREFIX = ts=
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
TRUNCATE = 10000

[lab:udp]
SHOULD_LINEMERGE = false
TIME_PREFIX = ts=
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
TRUNCATE = 10000

[lab:json]
SHOULD_LINEMERGE = false
INDEXED_EXTRACTIONS = json
TIMESTAMP_FIELDS = ts
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
TRUNCATE = 10000

[lab:otel]
SHOULD_LINEMERGE = false
INDEXED_EXTRACTIONS = json
TIMESTAMP_FIELDS = ts
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
TRUNCATE = 10000

[lab:xml]
SHOULD_LINEMERGE = false
TIME_PREFIX = ts="
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
TRUNCATE = 10000

[lab:hec]
SHOULD_LINEMERGE = false
INDEXED_EXTRACTIONS = json
TIMESTAMP_FIELDS = ts
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
TRUNCATE = 10000

[lab:scripted:python]
SHOULD_LINEMERGE = false
TIME_PREFIX = ts=
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
TRUNCATE = 10000

[lab:scripted:bash]
SHOULD_LINEMERGE = false
TIME_PREFIX = ts=
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
TRUNCATE = 10000

[lab:masked]
SHOULD_LINEMERGE = false
TIME_PREFIX = ts=
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3N%z
TRUNCATE = 10000

