[install]
is_configured = 1

[ui]
is_visible = 0
label = Network Input Examples

[launcher]
author = Learn Splunk
description = Defines TCP and UDP input examples for data source lessons.
version = 0.1.0

