[install]
is_configured = 1

[ui]
is_visible = 0
label = Forwarder Outputs To Heavy Forwarder

[launcher]
author = Splunk Learn Forwarding
description = Sends selected universal forwarder data to the heavy forwarder.
version = 0.1.0

